// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIB0o3o9RwCTXglVpYs57Msag7DMKRUxM',
    appId: '1:247614267061:web:c42dbde903dafcd765e8fc',
    messagingSenderId: '247614267061',
    projectId: 'sosialkita-18db3',
    authDomain: 'sosialkita-18db3.firebaseapp.com',
    storageBucket: 'sosialkita-18db3.firebasestorage.app',
    measurementId: 'G-6Z0WJN2DD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9oGP76ziTj_jcoHpsrDQlbmtjRnv5mqE',
    appId: '1:247614267061:android:d3aa858e69b63b6d65e8fc',
    messagingSenderId: '247614267061',
    projectId: 'sosialkita-18db3',
    storageBucket: 'sosialkita-18db3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIB0o3o9RwCTXglVpYs57Msag7DMKRUxM',
    appId: '1:247614267061:web:b237e06b5129dc8f65e8fc',
    messagingSenderId: '247614267061',
    projectId: 'sosialkita-18db3',
    authDomain: 'sosialkita-18db3.firebaseapp.com',
    storageBucket: 'sosialkita-18db3.firebasestorage.app',
    measurementId: 'G-86V3DLNXDG',
  );
}
